name: artfacts
on:
  workflow_dispatch:
    
env:
  AWS_REGION: us-east-1
  AWS_CLUSTER: cluster_eks
  ECR_REPO: vproapp

jobs:
  artifactsbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install maven
        id: mvn_install
        run: mvn install

      - name: mvn checkstyle
        id: checkstyle
        run: mvn checkstyle:checkstyle

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      - name: code analysis
        id: analysis
        run: sonar-scanner
           -Dsonar.host.url=${{ secrets.SONAR_URL }}
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
           -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
           -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY}}
           -Dsonar.sources=src/ 
           -Dsonar.junit.reportsPath=target/surefire-reports/
           -Dsonar.jacoco.reportsPath=target/jacoco.exec
           -Dsonar.java.checkstyle.reportsPath=target/checkstyle-result.xml
           -Dsonar.java.binaries=target/test-classes/com/visualpathit/account

      - name: quality gate
        id: gate
        if: steps.analysis.outcome == 'success'
        uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}

  build_and_run:
    runs-on: ubuntu-latest
    needs: artifactsbuild
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.ACCESS_KEY}}
          secret_key: ${{ secrets.SECRET_KEY }}
          registry: ${{ secrets.URL_ECR }}
          # cache_from: ${{ secrets.cache }}
          repo: ${{env.ECR_REPO}}
          region: ${{env.AWS_REGION}}
          auto_tag: true
          daemon_off: false
          dockerfile: ./Dockerfile
          context: vpro
            
        

    